name: grpc_bloc_helper
description: Flutter package to help managing gRPC calls with bloc pattern
version: 0.1.0
homepage: https://github.com/flrnsbt/grpc_bloc_helper

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_concurrency: ^0.2.2
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  grpc: ^3.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
